baseURL = 'https://jackypanster.github.io/ai-stream/'
languageCode = 'en-us'
title = 'AI Stream'
theme = 'PaperMod'

[params]
  author = "Jacky Pan"
  ShowSearch = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 20

  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 30