baseURL = 'https://jackypanster.github.io/ai-stream/'
languageCode = 'zh-cn'
title = 'Code Whispers'
theme = 'PaperMod'

[params]
    author = "Jacky Pan"
  description = "Code Whispers - 一个关于 AI、编程和技术的赛博空间。"
  keywords = ["Blog", "Portfolio", "Jacky Pan", "AI", "Tech"]
  ShowSearch = true

  ShowReadingTime = true
  ShowWordCount = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowToc = true
  TocOpen = true

  ShowRssButtonInSectionTermList = true
  ShowFullTextinRSS = false
  disableSpecial1stPost = false
  disableScrollToTop = false
  disableAnchoredHeadings = false
  hideMeta = false
  hideSummary = false
  hideFooter = false

  [[params.social_icons]]
    name = "github"
    url = "https://github.com/jackypanster"

  [params.comments.giscus]
    repo = "jackypanster/ai-stream"
    repoId = "R_kgDOOsWGYw"
    category = "General"
    categoryId = "DIC_kwDOOsWGY84CtB0U"
    mapping = "pathname"
    reactionsEnabled = "1"
    emitMetadata = "0"
    lang = "zh-CN"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 20

  [[menu.main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 30
